#<Main>:
#    Image:
#        source: "../res/screens/backgrounds/background.png"
#    EquipmentDisplay:
#        size_hint: 0.4, 0.265
#        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
#        canvas:
#            Color:
#                rgba: 1, 1, 0, 0.4
#            Rectangle:
#                size: self.size
#                pos: self.pos
#
#<EquipmentDisplay>:
#    Image:
#        id: background
#        source: '../res/screens/equip/background.png'
#    Label:
#        text: '[b]Vambraces[/b]'
#        markup: True
#        font_name: '../res/fnt/Gabriola.ttf'
#        font_size: self.height * 0.9
#        color: 0, 0, 0, 1
#        size_hint: None, 0.15
#        width: self.texture_size[0]
#        pos_hint: {'x': 0.025, 'top': 0.95}
#    Image:
#        id: type
#        source: '../res/screens/stats/MagicalAttack_black.png'
#        size_hint: 0.075, 0.15
#        pos_hint: {'x': 0.2625, 'top': 0.95}
#    Image:
#        id: element
#        source: '../res/screens/attribute/earth.png'
#        size_hint: 0.075, 0.15
#        pos_hint: {'x': 0.35, 'top': 0.95}
#    Image:
#        id: rank
#        source: '../res/screens/stats/sss.png'
#        size_hint: 0.125, 0.15
#        allow_stretch: True
#        pos_hint: {'x': 0.45, 'top': 0.95}
#    Image:
#        id: weapon_eq
#        source: '../res/screens/equip/slot.png'
#        size_hint: 0.55, 0.275
#        allow_stretch: True
#        pos_hint: {'x': 0.025, 'top': 0.75}
#    Label:
#        text: 'Leather Helm'
#        font_name: '../res/fnt/Gabriola.ttf'
#        font_size: self.height * 0.5
#        color: 0, 0, 0, 1
#        size_hint: 0.35, 0.275
#        pos_hint: {'x': 0.025, 'top': 0.75}
##        canvas:
##            Color:
##                rgba: 1, 0, 0, 0.4
##            Rectangle:
##                size: self.size
##                pos: self.pos
#    Image:
#        source: '../res/items/equipment/helmet_1.png'
#        size_hint: 0.1375, 0.275
#        pos_hint: {'right': 0.575, 'top': 0.75}
#    Label:
#        text: 'Durability:  100/900\nScore:           945\nValue:          10,000'
#        halign: 'left'
#        valign: 'top'
#        font_name: '../res/fnt/Gabriola.ttf'
#        font_size: root.height * 0.15
#        color: 0, 0, 0, 1
#        size_hint: None, None
#        size: self.texture_size
#        pos_hint: {'x': 0.025, 'top': 0.45}
###        canvas:
###            Color:
###                rgba: 1, 0, 0, 0.4
###            Rectangle:
###                size: self.size
###                pos: self.pos
#    ScrollView:
#        do_scroll_x: False
#        do_scroll_y: True
#        size_hint: 0.375, 0.9
#        pos_hint: {'right': 0.975, 'top': 0.95}
#        GridLayout:
#            cols: 2
#            size_hint_y: None
#            orientation: 'vertical'
#            height: self.minimum_height
#            Image:
#                id: patk
#                source: '../res/screens/stats/PhysicalAttack_black.png'
#                size_hint: 0.5, None
#                height: root.height * 0.15
#            Label:
#                text: '1000'
#                color: 0, 0, 0 ,1
#                font_name: '../res/fnt/Gabriola.ttf'
#            Image:
#                id: matk
#                source: '../res/screens/stats/MagicalAttack_black.png'
#                size_hint: 0.075, None
#                height: root.height * 0.15
#            Label:
#                text: '1000'
#                color: 0, 0, 0 ,1
#                font_name: '../res/fnt/Gabriola.ttf'
#            Image:
#                id: def
#                source: '../res/screens/stats/Defense_black.png'
#                size_hint: 0.075, None
#                height: root.height * 0.15
#            Label:
#                text: '1000'
#                color: 0, 0, 0 ,1
#                font_name: '../res/fnt/Gabriola.ttf'
#            Image:
#                id: health
#                source: '../res/screens/stats/Health_black.png'
#                size_hint: 0.075, None
#                height: root.height * 0.15
#            Label:
#                text: '1000'
#                color: 0, 0, 0 ,1
#                font_name: '../res/fnt/Gabriola.ttf'
#            Image:
#                id: mana
#                source: '../res/screens/stats/Mana_black.png'
#                size_hint: 0.075, None
#                height: root.height * 0.15
#            Label:
#                text: '1000'
#                color: 0, 0, 0 ,1
#                font_name: '../res/fnt/Gabriola.ttf'
#            Image:
#                id: str
#                source: '../res/screens/stats/Str_black.png'
#                size_hint: 0.075, None
#                height: root.height * 0.15
#            Label:
#                text: '1000'
#                color: 0, 0, 0 ,1
#                font_name: '../res/fnt/Gabriola.ttf'
#            Image:
#                id: mag
#                source: '../res/screens/stats/Mag_black.png'
#                size_hint: 0.075, None
#                height: root.height * 0.15
#            Label:
#                text: '1000'
#                color: 0, 0, 0 ,1
#                font_name: '../res/fnt/Gabriola.ttf'
#            Image:
#                id: end
#                source: '../res/screens/stats/End_black.png'
#                size_hint: 0.075, None
#                height: root.height * 0.15
#            Label:
#                text: '1000'
#                color: 0, 0, 0 ,1
#                font_name: '../res/fnt/Gabriola.ttf'
#            Image:
#                id: dex
#                source: '../res/screens/stats/Dex_black.png'
#                size_hint: 0.075, None
#                height: root.height * 0.15
#            Label:
#                text: '1000'
#                color: 0, 0, 0 ,1
#                font_name: '../res/fnt/Gabriola.ttf'
#            Image:
#                id: agi
#                source: '../res/screens/stats/Agi_black.png'
#                size_hint: 0.075, None
#                height: root.height * 0.15
#            Label:
#                text: '1000'
#                color: 0, 0, 0 ,1
#                font_name: '../res/fnt/Gabriola.ttf'
#    Image:
#        id: weapon_eq
#        source: '../res/screens/equip/list.png'
#        size_hint: 0.375, 0.9
#        allow_stretch: True
#        pos_hint: {'right': 0.975, 'top': 0.95}

<Main>:
    Image:
        source: "../res/screens/backgrounds/background.png"
        allow_stretch: True
    Carousel:
        id: carousel
        direction: 'bottom'
        RelativeLayout:
            GridLayout:
                cols: 8
                rows: 1
                size_hint: 1, 0.225
                pos_hint: {'center_x': 0.5, 'top': 1}
                padding: [root.height * 0.025, root.height * 0.025, root.height * 0.025, 0]
                spacing: root.height * 0.0125
        #        canvas:
        #            Color:
        #                rgba: 1, 1, 0, 0.4
        #            Rectangle:
        #                size: self.size
        #                pos: self.pos
                CharEquipButton:
                CharEquipButton:
                CharEquipButton:
                CharEquipButton:
                CharEquipButton:
                CharEquipButton:
                CharEquipButton:
                CharEquipButton:

            GridLayout:
                cols: 8
                rows: 1
                padding: [root.height * 0.025, root.height * 0.0125, root.height * 0.025, 0]
                spacing: root.height * 0.0125
                size_hint: 1, 0.625
                pos_hint: {'center_x': 0.5, 'top': 0.775}
        #        canvas:
        #            Color:
        #                rgba: 1, 1, 0, 0.4
        #            Rectangle:
        #                size: self.size
        #                pos: self.pos
                EquipmentDisplay:
                EquipmentDisplay:
                EquipmentDisplay:
                EquipmentDisplay:
                EquipmentDisplay:
                EquipmentDisplay:
                EquipmentDisplay:
                EquipmentDisplay:
            Button:
                size_hint: 0.2, 0.1
                pos_hint: {'center_x': 0.5, 'y': 0.025}
                on_release: carousel.load_next()
        RelativeLayout:
            Button:
                size_hint: 0.2, 0.1
                pos_hint: {'center_x': 0.5, 'top': 0.975}
                on_release: carousel.load_previous()
            GridLayout:
                cols: 8
                rows: 1
                size_hint: 1, 0.225
                pos_hint: {'center_x': 0.5, 'y': 0.65}
                padding: [root.height * 0.025, root.height * 0.025, root.height * 0.025, 0]
                spacing: root.height * 0.0125
        #        canvas:
        #            Color:
        #                rgba: 1, 1, 0, 0.4
        #            Rectangle:
        #                size: self.size
        #                pos: self.pos
                CharEquipButton:
                CharEquipButton:
                CharEquipButton:
                CharEquipButton:
                CharEquipButton:
                CharEquipButton:
                CharEquipButton:
                CharEquipButton:

            GridLayout:
                cols: 8
                rows: 1
                padding: [root.height * 0.025, root.height * 0.0125, root.height * 0.025, 0]
                spacing: root.height * 0.0125
                size_hint: 1, 0.625
                pos_hint: {'center_x': 0.5, 'y': 0.025}
        #        canvas:
        #            Color:
        #                rgba: 1, 1, 0, 0.4
        #            Rectangle:
        #                size: self.size
        #                pos: self.pos
                EquipmentDisplay:
                EquipmentDisplay:
                EquipmentDisplay:
                EquipmentDisplay:
                EquipmentDisplay:
                EquipmentDisplay:
                EquipmentDisplay:
                EquipmentDisplay:


<CharEquipButton>:
    Image:
        source: '../res/characters/test/cave_dwellers_sofi_and_claire/cave_dwellers_sofi_and_claire_preview.png'
        size_hint: 0.98, 0.98
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    Image:
        source: '../res/screens/equip/preview_background.png'
    Button:
        on_release: print("Goto Char screen!")
        opacity: 0

<EquipmentDisplay>:
#    ImageH:
#        source: '../res/screens/equip/long_background.png'
#    canvas:
#        Color:
#            rgba: 1, 0.2, 1, 0.4
#        Rectangle:
#            size: self.size
#            pos: self.pos
    GridLayout:
        rows: 9
        cols: 1
        spacing: [0, ((self.height / 9) - (self.width * 50 / 200)) * 9 / 8]
        EquipItem:
        EquipItem:
        EquipItem:
        EquipItem:
        EquipItem:
        EquipItem:
        EquipItem:
        EquipItem:
        EquipItem:

<EquipItem>:
    Image:
        source: '../res/screens/equip/slot.png'
    Button:
        on_release:  print('pressed me!')
        opacity: 0