HEADER_SIZE = 332
HEADER_SIZE_COMPAT = 324

FORMAT_VERSION = b'\x14\x12\x11'
FORMAT_VERSION_COMPAT_0 = b'\x13\x12\x11'
FORMAT_VERSION_COMPAT_1 = b'\x12\x10\x10'

FORMAT_TYPE = b'\x00'

OPTION_USE_SCRIPT = 1
OPTION_USE_TEXTUREATLAS = 2
OPTION_COMPRESSED = 4
OPTION_USE_LUASCRIPT = 8

MATRIX_FLAG = (1 << 31)
MATRIX_FLAG_MASK = MATRIX_FLAG
COLOR_TRANSFORM_FLAG = (1 << 31)

TEXTURE_FORMAT_NORMAL = 0
TEXTURE_FORMAT_PREMULTIPLIED_ALPHA = 1

BLEND_MODE_NORMAL = 0
BLEND_MODE_ADD = 1
BLEND_MODE_LAYER = 2
BLEND_MODE_ERASE = 3
BLEND_MODE_MASK = 4
BLEND_MODE_MULTIPLY = 5
BLEND_MODE_SCREEN = 6
BLEND_MODE_SUBTRACT = 7
