<ImagePreview>:
    Image:
        id: background
        source: root.background_source
        allow_stretch: True
    Image:
        id: char_image
        source: root.char_image_source
        allow_stretch: True
    PPCHoverPathButton:
        id: back_button
        path: 'buttons/back'
        size_hint: app.get_dkey('bb s_h')
        pos_hint: app.get_dkey('bb p_h')
        on_release: root.on_back_press()