__all__ = ('Constant',)


class Constant:
    HEADER_SIZE = 332
    FORMAT_VERSION_0 = 0x14
    FORMAT_VERSION_1 = 0x12
    FORMAT_VERSION_2 = 0x11
    FORMAT_VERSION_141211 = 0x141211

    HEADER_SIZE_COMPAT_0 = 324
    FORMAT_VERSION_COMPAT_0_0 = 0x13
    FORMAT_VERSION_COMPAT_0_1 = 0x12
    FORMAT_VERSION_COMPAT_0_2 = 0x11

    HEADER_SIZE_COMPAT_1 = 324
    FORMAT_VERSION_COMPAT_1_0 = 0x12
    FORMAT_VERSION_COMPAT_1_1 = 0x10
    FORMAT_VERSION_COMPAT_1_2 = 0x10

    FORMAT_TYPE = 0

    OPTION_USE_SCRIPT = (1 << 0)
    OPTION_USE_TEXTUREATLAS = (1 << 1)
    OPTION_COMPRESSED = (1 << 2)
    OPTION_USE_LUASCRIPT = (1 << 3)

    MATRIX_FLAG = (1 << 31)
    MATRIX_FLAG_MASK = MATRIX_FLAG
    COLOR_TRANSFORM_FLAG = (1 << 31)

    TEXTURE_FORMAT_NORMAL = 0
    TEXTURE_FORMAT_PREMULTIPLIED_ALPHA = 1

    BLEND_MODE_NORMAL = 0
    BLEND_MODE_ADD = 1
    BLEND_MODE_LAYER = 2
    BLEND_MODE_ERASE = 3
    BLEND_MODE_MASK = 4
    BLEND_MODE_MULTIPLY = 5
    BLEND_MODE_SCREEN = 6
    BLEND_MODE_SUBTRACT = 7
