END = 0
PLAY = 1
STOP = 2
NEXTFRAME = 3
PREVFRAME = 4
GOTOFRAME = 5  # FRAMENO(4bytes)
GOTOLABEL = 6  # LABELID(4bytes)
SETTARGET = 7  # COUNT(1byte) INSTANCEID(4bytes)
# SETTARGET 0           :myself
# SETTARGET 1 ROOT      :root
# SETTARGET 1 PARENT    :parent
# SETTARGET 1 ID        :child
# SETTARGET 2 PARENT ID :sibling
# SETTARGET 2 ROOT ID   :root/child
EVENT = 8
CALL = 9
INSTANCE_TARGET_ROOT = -1
INSTANCE_TARGET_PARENT = -2
