<IconTray>:
    viewclass: 'Image'
    RecycleGridLayout:
        height: self.minimum_height
        cols: 6
#        rows: 4

        orientation: 'lr-bt'

        default_size_hint: None, None
        default_size: self.width * 0.167, self.width * 0.16
        col_default_width: self.width * 0.167
        row_default_height: self.width * 0.167
        col_force_default: True
        row_force_default: True
